# Generated by Django 3.2.4 on 2021-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_files_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
