# Generated by Django 3.2.4 on 2021-06-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210605_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['pdf']},
        ),
        migrations.RemoveField(
            model_name='files',
            name='title',
        ),
    ]
